CREATE TABLE IF NOT EXISTS machines (
  id VARCHAR(36) CHARACTER SET utf8 NOT NULL,
  name VARCHAR(255) CHARACTER SET utf8 NOT NULL,
  description TEXT CHARACTER SET utf8,
  serialNumber VARCHAR(255) CHARACTER SET utf8,
  location VARCHAR(255) CHARACTER SET utf8,
  isActive TINYINT(1) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);