CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT NOT NULL,
  email VARCHAR(255) CHARACTER SET utf8 NOT NULL,
  passwordHash VARCHAR(255) CHARACTER SET utf8 NOT NULL,
  role VARCHAR(50) CHARACTER SET utf8 NOT NULL,
  permissions TEXT CHARACTER SET utf8,
  isActive TINYINT(1) NOT NULL,
  UNIQUE KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
