CREATE TABLE migrations (
  id INTEGER NOT NULL,
  name VARCHAR(255) NOT NULL,
  run_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);

CREATE SEQUENCE migrations_seq;

SET TERM !! ;
CREATE TRIGGER migrations_bi FOR migrations
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.id IS NULL) THEN
    NEW.id = NEXT VALUE FOR migrations_seq;
END!!
SET TERM ; !!