/**
 * Logs an audit log entry into the database.
 * @module core/audit/AuditLogService
 * @param entry - The audit log entry to log. This object must contain the following properties:
 *   - id: The id of the audit log entry. This is automatically generated by the system.
 *   - timestamp: The timestamp of the audit log entry. This is automatically generated by the system.
 *   - userId: The id of the user who performed the action that triggered this audit log entry.
 *   - action: The action that triggered this audit log entry.
 *   - entity: The entity that was affected by the action that triggered this audit log entry.
 *   - entityId: The id of the entity that was affected by the action that triggered this audit log entry.
 *   - details: Any additional details about the audit log entry.
 */

import type { DatabaseAdapter } from "../db/DatabaseAdapter";
import { TABLES } from "../db/schema/tables";

export interface AuditLogEntry {
  id: string;
  timestamp: number;
  userId: string;
  action: string;
  entity: string;
  entityId: string;
  details?: any;
}

export class AuditLogService {
  constructor(private db: DatabaseAdapter) {}
  
  /**
   * Logs an audit log entry into the database.
   * @param entry - The audit log entry to log. This object must contain the following properties:
   *   - id: The id of the audit log entry. This is automatically generated by the system.
   *   - timestamp: The timestamp of the audit log entry. This is automatically generated by the system.
   *   - userId: The id of the user who performed the action that triggered this audit log entry.
   *   - action: The action that triggered this audit log entry.
   *   - entity: The entity that was affected by the action that triggered this audit log entry.
   *   - entityId: The id of the entity that was affected by the action that triggered this audit log entry.
   *   - details: Any additional details about the audit log entry.
   */
  async log(entry: Omit<AuditLogEntry, "id" | "timestamp">) {
    const full: AuditLogEntry = {
      id: crypto.randomUUID(),
      timestamp: Date.now(),
      ...entry
    };

    await this.db.insert(TABLES.audit_logs, full);
  }
}