CREATE TABLE machines (
  id VARCHAR(36) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description BLOB SUB_TYPE TEXT,
  serialNumber VARCHAR(255),
  location VARCHAR(255),
  isActive SMALLINT NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);